In [1]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [2]:
data = pd.read_csv("jester-data-1.csv", header= None)
d = data.to_latex()
text_file = open("OutputExcersice.txt", "w")
text_file.write(d)
text_file.close()

In [3]:
n_features = 2

training_set = data.values[:19986]

user_ratings = training_set
user_preferences = np.random.random((user_ratings.shape[0], n_features))
item_features = np.random.random((user_ratings.shape[1],n_features))

In [4]:
data.values.shape

(24983, 101)

In [5]:
item_features

array([[ 0.845,  0.089],
       [ 0.448,  0.309],
       [ 0.869,  0.974],
       [ 0.795,  0.759],
       [ 0.478,  0.667],
       [ 0.619,  0.771],
       [ 0.171,  0.698],
       [ 0.74 ,  0.65 ],
       [ 0.118,  0.943],
       [ 0.861,  0.013],
       [ 0.491,  0.826],
       [ 0.359,  0.143],
       [ 0.636,  0.891],
       [ 0.779,  0.386],
       [ 0.613,  0.742],
       [ 0.3  ,  0.816],
       [ 0.375,  0.903],
       [ 0.727,  0.646],
       [ 0.677,  0.582],
       [ 0.958,  0.191],
       [ 0.423,  0.61 ],
       [ 0.141,  0.394],
       [ 0.52 ,  0.676],
       [ 0.917,  0.404],
       [ 0.782,  0.313],
       [ 0.031,  0.31 ],
       [ 0.398,  0.611],
       [ 0.628,  0.548],
       [ 0.702,  0.502],
       [ 0.648,  0.822],
       [ 0.201,  0.414],
       [ 0.231,  0.968],
       [ 0.407,  0.47 ],
       [ 0.867,  0.933],
       [ 0.81 ,  0.101],
       [ 0.079,  0.551],
       [ 0.237,  0.774],
       [ 0.643,  0.405],
       [ 0.526,  0.608],
       [ 0.397,  0.621],


In [6]:
user_preferences

array([[ 0.055,  0.756],
       [ 0.985,  0.562],
       [ 0.674,  0.425],
       ..., 
       [ 0.405,  0.323],
       [ 0.254,  0.795],
       [ 0.637,  0.161]])

In [7]:
user_ratings[user_ratings == 99] = np.NaN

In [8]:
training_set = np.delete(user_ratings,0,1)

In [9]:
user_preferences

array([[ 0.055,  0.756],
       [ 0.985,  0.562],
       [ 0.674,  0.425],
       ..., 
       [ 0.405,  0.323],
       [ 0.254,  0.795],
       [ 0.637,  0.161]])

In [10]:
def predict_rating(user_id,item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = user_preferences[user_id]
    item_preference = item_features[item_id]
    return user_preference.dot(item_preference)

def train(user_id, item_id, rating,alpha = 0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err = ( prediction_rating- rating );
    #print err
    user_pref_values = user_preferences[user_id][:]
    user_preferences[user_id] -= alpha * err * item_features[item_id]
    item_features[item_id] -= alpha * err * user_pref_values
    return err
    


def sgd(iterations = 10):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(0,iterations):
        error = []
        for user_id in range(0,user_preferences.shape[0]):
            for item_id in range(0,item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if(not np.isnan(rating)):
                    err = train(user_id,item_id,rating)
                    error.append(err)
    mse = (np.array(error) ** 2).mean()          
    print mse

def mse(iterations = 10):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(0,iterations):
        error = []
        for user_id in range(0,user_preferences.shape[0]):
            for item_id in range(0,item_features.shape[0]):
                rating = validation_set[user_id][item_id]
                if(not np.isnan(rating)):
                    err = train(user_id,item_id,rating)
                    error.append(err)
    mse = (np.array(error) ** 2).mean()          
    print mse
                    

In [11]:
for (x,y), value in np.ndenumerate(training_set):
    if np.isnan(value):
        training_set[x,y] = predict_rating(x,y)
training_set

array([[-7.82 ,  8.79 , -9.66 , ...,  0.631,  0.616,  0.115],
       [ 4.08 , -0.29 ,  6.36 , ...,  0.34 , -4.32 ,  1.07 ],
       [ 0.607,  0.433,  0.999, ...,  0.573,  0.647,  0.479],
       ..., 
       [-0.68 , -4.56 ,  4.13 , ...,  7.23 ,  6.7  ,  4.13 ],
       [ 0.285,  0.359,  0.994, ...,  0.73 ,  0.739,  0.247],
       [ 2.04 , -2.23 ,  1.99 , ...,  0.83 ,  3.16 , -0.29 ]])

In [12]:
np.isnan(training_set[2,0])

False

In [13]:
validation_set = data.values[19987:22484]

In [14]:
validation_set[validation_set == 99] = np.NaN

In [15]:
sgd()

24.4242401756


In [30]:
ratings = data.values
ratings = np.delete(ratings,0,1)
ratings[ratings == 99] = np.NaN
smallest = 1000000
largest = -1000000
smallest_indx, largest_indx = -1, -1
for index,column in enumerate(ratings.T):
    column = column[~np.isnan(column)]
    mean = column.mean()
    if mean > largest:
        largest = mean
        largest_indx = index
    if mean < smallest:
        smallest = mean
        smallest_indx = index
        
print 'best joke with index:', largest_indx, largest
print 'worst joke with index:', smallest_indx, smallest

best joke with index: 49 3.66508489508
worst joke with index: 57 -3.83387963737


In [27]:
ratings = data.values
ratings = np.delete(ratings,0,1)
user_ratings[user_ratings == 99] = np.NaN
ratings

array([[ -7.82,   8.79,  -9.66, ...,  99.  ,  99.  ,  99.  ],
       [  4.08,  -0.29,   6.36, ...,   0.34,  -4.32,   1.07],
       [ 99.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       ..., 
       [ 99.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       [ 99.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       [  2.43,   2.67,  -3.98, ...,  99.  ,  99.  ,  99.  ]])

In [21]:
arr[~np.isnan(arr)]

array([ 1.,  1.,  1.])